### ISSUE TITLE
stack value has undefined for values.

### ISSUE THREAD

**Issue by robross0606** [nickuraltsev/composite-error#2]
After creating a composite error, the result is that `innerErrors` contains the string messages for all the expected errors.  
```
[
      "Term (1.0_15571108706641871406552) referenced in relationship (represent-element) cannot be found.",
      "Term (1.0_15571108235121756500925) referenced in relationship (represent-element) cannot be found.",
      "Term (1.0_1557110627098-1963619659) referenced in relationship (represent-element) cannot be found.",
      "Term (1.0_1557110802238-1919010934) referenced in relationship (represent-element) cannot be found.",
      "Term (1.0_15571108133752086874573) referenced in relationship (represent-element) cannot be found."
]
```
However, the stack contains `undefined` for all the steps:

```
"CompositeError: One or more errors occurred while setting up terminology relatonships from MDR
    at Object.refreshTerminologyFromMdr (C:\Code\ncp\study-design-service\src\mdr-service.js:212:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async refreshMdrCache (C:\Code\ncp\study-design-service\index.js:70:5)
--- Inner error #0: undefined
--- End of inner error
--- Inner error #1: undefined
--- End of inner error
--- Inner error #2: undefined
--- End of inner error
--- Inner error #3: undefined
--- End of inner error
--- Inner error #4: undefined
--- End of inner error"
```

**Comment by robross0606** [comment]
Nevermind, this was a bogus issue created upstream of composite-error.
